name: test-install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test-install
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
          export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session --print-address --fork`
          make
      - name: aptfile
        run: ./aptfile
